"""
tests/test_handoff_publisher.py — Sprint 7F handoff publisher tests.

Classification: production runtime test
Sprint: 7F

Tests:
  Group 1  — File existence and output generation
  Group 2  — Active universe validation
  Group 3  — Current manifest validation
  Group 4  — Publisher report validation
  Group 5  — Heartbeat validation
  Group 6  — Safety flags and invariants
  Group 7  — Fail-closed conditions
  Group 8  — Atomic write policy
  Group 9  — Import safety (AST)
  Group 10 — Regression (Sprint 7E, 7C, smoke)

No broker calls, no LLM calls, no live API calls.
"""
from __future__ import annotations

import ast
import json
import os
import shutil
import sys
import tempfile
import unittest
from datetime import datetime, timedelta, timezone
from unittest.mock import patch

import pytest

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _future_iso(minutes: int = 30) -> str:
    dt = datetime.now(timezone.utc) + timedelta(minutes=minutes)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _past_iso(hours: int = 2) -> str:
    dt = datetime.now(timezone.utc) - timedelta(hours=hours)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _minimal_shadow_candidate(symbol: str = "NVDA") -> dict:
    return {
        "symbol": symbol,
        "company_name": None,
        "asset_type": "equity",
        "reason_to_care": "economic_intelligence",
        "bucket_id": f"econ_{symbol}",
        "bucket_type": "structural",
        "route": "swing",
        "source_labels": ["economic_intelligence_feed"],
        "macro_rules_fired": ["ai_capex_growth_to_semiconductors"],
        "transmission_direction": "tailwind",
        "company_validation_status": "not_run_static_bootstrap",
        "thesis_intact": None,
        "why_this_symbol": f"{symbol} is an economic intelligence candidate",
        "invalidation": [],
        "eligibility": {"status": "shadow_only_unknown", "reason": "static bootstrap", "symbol": symbol},
        "quota": {"group": "structural_position", "protected": False},
        "execution_instructions": {
            "executable": False,
            "allowed_routes_when_live": ["position", "swing"],
            "required_future_confirmation": ["live_spread_and_risk_check_at_execution_only"],
            "note": "Shadow only",
        },
        "risk_notes": [],
        "live_output_changed": False,
    }


def _minimal_shadow_universe(symbols: list[str] | None = None) -> dict:
    syms = symbols or ["NVDA", "AAPL", "MSFT"]
    return {
        "schema_version": "1.0",
        "generated_at": _now_iso(),
        "valid_for_session": _future_iso(240),
        "freshness_status": "fresh",
        "mode": "shadow_only",
        "source_files": ["data/intelligence/economic_candidate_feed.json"],
        "universe_summary": {
            "total_candidates": len(syms),
            "structural_candidates": len(syms),
            "manual_candidates": 0,
            "attention_candidates": 0,
            "etf_proxy_candidates": 0,
        },
        "quota_summary": {},
        "quota_pressure_diagnostics": {},
        "source_collision_report": {},
        "adapter_usage_summary": {},
        "candidates": [_minimal_shadow_candidate(s) for s in syms],
        "inclusion_log": [],
        "exclusion_log": [],
        "warnings": [],
    }


def _load_publisher_output(filename: str) -> dict:
    path = os.path.join(_ROOT, "data", "live", filename)
    with open(path) as f:
        return json.load(f)


def _load_heartbeat() -> dict:
    path = os.path.join(_ROOT, "data", "heartbeats", "handoff_publisher.json")
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Group 1 — File existence and output generation
# ---------------------------------------------------------------------------

class TestOutputFilesExist(unittest.TestCase):
    """Group 1: All four output files generated by publisher."""

    def test_handoff_publisher_module_exists(self):
        """handoff_publisher.py exists in repo root."""
        self.assertTrue(os.path.exists(os.path.join(_ROOT, "handoff_publisher.py")))

    def test_active_opportunity_universe_generated(self):
        """data/live/active_opportunity_universe.json exists."""
        self.assertTrue(
            os.path.exists(os.path.join(_ROOT, "data/live/active_opportunity_universe.json"))
        )

    def test_current_manifest_generated(self):
        """data/live/current_manifest.json exists."""
        self.assertTrue(
            os.path.exists(os.path.join(_ROOT, "data/live/current_manifest.json"))
        )

    def test_publisher_report_generated(self):
        """data/live/handoff_publisher_report.json exists."""
        self.assertTrue(
            os.path.exists(os.path.join(_ROOT, "data/live/handoff_publisher_report.json"))
        )

    def test_heartbeat_generated(self):
        """data/heartbeats/handoff_publisher.json exists."""
        self.assertTrue(
            os.path.exists(os.path.join(_ROOT, "data/heartbeats/handoff_publisher.json"))
        )


# ---------------------------------------------------------------------------
# Group 2 — Active universe validation
# ---------------------------------------------------------------------------

class TestActiveUniverse(unittest.TestCase):
    """Group 2: active_opportunity_universe.json structure and invariants."""

    def setUp(self):
        self.data = _load_publisher_output("active_opportunity_universe.json")

    def test_active_universe_is_dict(self):
        self.assertIsInstance(self.data, dict)

    def test_mode_is_production_handoff_universe(self):
        self.assertEqual(self.data.get("mode"), "production_handoff_universe")

    def test_publication_mode_is_validation_only(self):
        self.assertEqual(self.data.get("publication_mode"), "validation_only")

    def test_validation_status_is_pass(self):
        self.assertEqual(self.data.get("validation_status"), "pass")

    def test_no_executable_trade_instructions(self):
        self.assertIs(self.data.get("no_executable_trade_instructions"), True)

    def test_live_output_changed_false(self):
        self.assertIs(self.data.get("live_output_changed"), False)

    def test_secrets_exposed_false(self):
        self.assertIs(self.data.get("secrets_exposed"), False)

    def test_env_values_logged_false(self):
        self.assertIs(self.data.get("env_values_logged"), False)

    def test_candidates_is_nonempty_list(self):
        candidates = self.data.get("candidates")
        self.assertIsInstance(candidates, list)
        self.assertGreater(len(candidates), 0)

    def test_no_candidate_executable(self):
        for c in self.data.get("candidates", []):
            self.assertIsNot(c.get("executable"), True,
                             f"candidate {c.get('symbol')} has executable=true")

    def test_no_order_instruction(self):
        for c in self.data.get("candidates", []):
            self.assertIsNone(c.get("order_instruction"),
                              f"candidate {c.get('symbol')} has non-null order_instruction")

    def test_all_candidates_have_symbol(self):
        for c in self.data.get("candidates", []):
            self.assertTrue(c.get("symbol"), f"candidate missing symbol: {c}")

    def test_all_candidates_have_route(self):
        for c in self.data.get("candidates", []):
            self.assertTrue(c.get("route"), f"candidate {c.get('symbol')} missing route")

    def test_all_candidates_have_route_hint(self):
        for c in self.data.get("candidates", []):
            self.assertIsInstance(c.get("route_hint"), list,
                                  f"candidate {c.get('symbol')} missing route_hint")

    def test_all_candidates_have_reason_to_care(self):
        for c in self.data.get("candidates", []):
            self.assertTrue(c.get("reason_to_care") is not None,
                            f"candidate {c.get('symbol')} missing reason_to_care")

    def test_all_candidates_have_source_labels(self):
        for c in self.data.get("candidates", []):
            self.assertIsInstance(c.get("source_labels"), list,
                                  f"candidate {c.get('symbol')} missing source_labels")
            self.assertGreater(len(c.get("source_labels", [])), 0,
                               f"candidate {c.get('symbol')} has empty source_labels")

    def test_all_candidates_have_risk_flags(self):
        for c in self.data.get("candidates", []):
            self.assertIsInstance(c.get("risk_flags"), list,
                                  f"candidate {c.get('symbol')} missing risk_flags")

    def test_candidate_live_output_changed_false(self):
        for c in self.data.get("candidates", []):
            self.assertIs(c.get("live_output_changed"), False,
                          f"candidate {c.get('symbol')} has live_output_changed!=false")

    def test_schema_version_present(self):
        self.assertIn("schema_version", self.data)

    def test_generated_at_present(self):
        self.assertIn("generated_at", self.data)

    def test_expires_at_present(self):
        self.assertIn("expires_at", self.data)

    def test_source_shadow_file_correct(self):
        self.assertEqual(
            self.data.get("source_shadow_file"),
            "data/universe_builder/active_opportunity_universe_shadow.json",
        )


# ---------------------------------------------------------------------------
# Group 3 — Current manifest validation
# ---------------------------------------------------------------------------

class TestCurrentManifest(unittest.TestCase):
    """Group 3: current_manifest.json structure and invariants."""

    def setUp(self):
        self.data = _load_publisher_output("current_manifest.json")

    def test_manifest_is_dict(self):
        self.assertIsInstance(self.data, dict)

    def test_handoff_enabled_false(self):
        self.assertIs(self.data.get("handoff_enabled"), False)

    def test_publication_mode_validation_only(self):
        self.assertEqual(self.data.get("publication_mode"), "validation_only")

    def test_enable_flag_required_true(self):
        self.assertIs(self.data.get("enable_flag_required"), True)

    def test_validation_status_present(self):
        self.assertIn("validation_status", self.data)

    def test_no_executable_trade_instructions(self):
        self.assertIs(self.data.get("no_executable_trade_instructions"), True)

    def test_live_output_changed_false(self):
        self.assertIs(self.data.get("live_output_changed"), False)

    def test_secrets_exposed_false(self):
        self.assertIs(self.data.get("secrets_exposed"), False)

    def test_env_values_logged_false(self):
        self.assertIs(self.data.get("env_values_logged"), False)

    def test_active_universe_file_references_existing_file(self):
        auf = self.data.get("active_universe_file")
        self.assertTrue(auf, "active_universe_file is empty")
        self.assertTrue(
            os.path.exists(os.path.join(_ROOT, auf)),
            f"active_universe_file does not exist: {auf}",
        )

    def test_publisher_is_handoff_publisher(self):
        self.assertEqual(self.data.get("publisher"), "handoff_publisher")

    def test_source_snapshot_versions_is_dict(self):
        self.assertIsInstance(self.data.get("source_snapshot_versions"), dict)

    def test_schema_version_present(self):
        self.assertIn("schema_version", self.data)

    def test_published_at_present(self):
        self.assertIn("published_at", self.data)

    def test_expires_at_present(self):
        self.assertIn("expires_at", self.data)


# ---------------------------------------------------------------------------
# Group 4 — Publisher report validation
# ---------------------------------------------------------------------------

class TestPublisherReport(unittest.TestCase):
    """Group 4: handoff_publisher_report.json structure and invariants."""

    def setUp(self):
        self.data = _load_publisher_output("handoff_publisher_report.json")

    def test_report_is_dict(self):
        self.assertIsInstance(self.data, dict)

    def test_mode_is_handoff_publisher_report(self):
        self.assertEqual(self.data.get("mode"), "handoff_publisher_report")

    def test_publication_mode_validation_only(self):
        self.assertEqual(self.data.get("publication_mode"), "validation_only")

    def test_handoff_enabled_false(self):
        self.assertIs(self.data.get("handoff_enabled"), False)

    def test_enable_flag_state_false(self):
        self.assertIs(self.data.get("enable_active_opportunity_universe_handoff_config_state"), False)

    def test_live_output_changed_false(self):
        self.assertIs(self.data.get("live_output_changed"), False)

    def test_production_candidate_source_changed_false(self):
        self.assertIs(self.data.get("production_candidate_source_changed"), False)

    def test_scanner_output_changed_false(self):
        self.assertIs(self.data.get("scanner_output_changed"), False)

    def test_apex_input_changed_false(self):
        self.assertIs(self.data.get("apex_input_changed"), False)

    def test_risk_logic_changed_false(self):
        self.assertIs(self.data.get("risk_logic_changed"), False)

    def test_order_logic_changed_false(self):
        self.assertIs(self.data.get("order_logic_changed"), False)

    def test_broker_called_false(self):
        self.assertIs(self.data.get("broker_called"), False)

    def test_trading_api_called_false(self):
        self.assertIs(self.data.get("trading_api_called"), False)

    def test_llm_called_false(self):
        self.assertIs(self.data.get("llm_called"), False)

    def test_raw_news_used_false(self):
        self.assertIs(self.data.get("raw_news_used"), False)

    def test_broad_intraday_scan_used_false(self):
        self.assertIs(self.data.get("broad_intraday_scan_used"), False)

    def test_validation_summary_is_dict(self):
        self.assertIsInstance(self.data.get("validation_summary"), dict)

    def test_candidate_summary_is_dict(self):
        self.assertIsInstance(self.data.get("candidate_summary"), dict)

    def test_overall_status_pass(self):
        vs = self.data.get("validation_summary") or {}
        self.assertEqual(vs.get("overall_status"), "pass")


# ---------------------------------------------------------------------------
# Group 5 — Heartbeat validation
# ---------------------------------------------------------------------------

class TestHeartbeat(unittest.TestCase):
    """Group 5: handoff_publisher heartbeat structure."""

    def setUp(self):
        self.data = _load_heartbeat()

    def test_heartbeat_is_dict(self):
        self.assertIsInstance(self.data, dict)

    def test_worker_is_handoff_publisher(self):
        self.assertEqual(self.data.get("worker"), "handoff_publisher")

    def test_validation_status_pass(self):
        self.assertEqual(self.data.get("validation_status"), "pass")

    def test_candidate_count_positive(self):
        self.assertGreater(self.data.get("candidate_count", 0), 0)

    def test_fail_closed_reason_none(self):
        self.assertIsNone(self.data.get("fail_closed_reason"))

    def test_live_output_changed_false(self):
        self.assertIs(self.data.get("live_output_changed"), False)

    def test_secrets_exposed_false(self):
        self.assertIs(self.data.get("secrets_exposed"), False)

    def test_env_values_logged_false(self):
        self.assertIs(self.data.get("env_values_logged"), False)


# ---------------------------------------------------------------------------
# Group 6 — Safety flags and configuration invariants
# ---------------------------------------------------------------------------

class TestSafetyInvariants(unittest.TestCase):
    """Group 6: Production safety flags and config invariants."""

    def test_publication_mode_is_validation_only(self):
        """Publication mode must be validation_only for Sprint 7F."""
        data = _load_publisher_output("active_opportunity_universe.json")
        self.assertEqual(data.get("publication_mode"), "validation_only")

    def test_handoff_enabled_false_in_manifest(self):
        """handoff_enabled must remain false in Sprint 7F."""
        data = _load_publisher_output("current_manifest.json")
        self.assertIs(data.get("handoff_enabled"), False)

    def test_enable_active_opportunity_universe_handoff_config_false(self):
        """enable_active_opportunity_universe_handoff config state must be false."""
        sys.path.insert(0, _ROOT)
        import config
        val = config.CONFIG.get("enable_active_opportunity_universe_handoff", False)
        self.assertFalse(val)

    def test_publisher_does_not_modify_bot_trading(self):
        """handoff_publisher.py source does not import or call bot_trading."""
        src_path = os.path.join(_ROOT, "handoff_publisher.py")
        tree = ast.parse(open(src_path).read())
        imports: set[str] = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name.split(".")[0])
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module.split(".")[0])
        self.assertNotIn("bot_trading", imports)


# ---------------------------------------------------------------------------
# Group 7 — Fail-closed conditions (unit tests using temp files)
# ---------------------------------------------------------------------------

class TestFailClosedConditions(unittest.TestCase):
    """Group 7: Publisher fails closed on invalid inputs without overwriting valid output."""

    def _run_with_shadow(self, shadow_data: dict) -> dict:
        """Run publisher with a custom shadow universe using a temp file."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            shadow_path = os.path.join(tmpdir, "shadow.json")
            with open(shadow_path, "w") as f:
                json.dump(shadow_data, f)

            sentinel_universe = os.path.join(tmpdir, "active_opportunity_universe.json")
            sentinel_manifest = os.path.join(tmpdir, "current_manifest.json")
            sentinel_report = os.path.join(tmpdir, "handoff_publisher_report.json")
            sentinel_heartbeat = os.path.join(tmpdir, "heartbeats", "handoff_publisher.json")

            with (
                patch.object(hp, "_SHADOW_UNIVERSE_PATH", shadow_path),
                patch.object(hp, "_OUTPUT_UNIVERSE", sentinel_universe),
                patch.object(hp, "_OUTPUT_MANIFEST", sentinel_manifest),
                patch.object(hp, "_OUTPUT_REPORT", sentinel_report),
                patch.object(hp, "_OUTPUT_HEARTBEAT", sentinel_heartbeat),
            ):
                report = hp.run_publisher()
            return report

    def _run_with_missing_shadow(self) -> dict:
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            missing_path = os.path.join(tmpdir, "nonexistent.json")
            sentinel_universe = os.path.join(tmpdir, "active_opportunity_universe.json")
            sentinel_manifest = os.path.join(tmpdir, "current_manifest.json")
            sentinel_report = os.path.join(tmpdir, "handoff_publisher_report.json")
            sentinel_heartbeat = os.path.join(tmpdir, "heartbeats", "handoff_publisher.json")
            with (
                patch.object(hp, "_SHADOW_UNIVERSE_PATH", missing_path),
                patch.object(hp, "_OUTPUT_UNIVERSE", sentinel_universe),
                patch.object(hp, "_OUTPUT_MANIFEST", sentinel_manifest),
                patch.object(hp, "_OUTPUT_REPORT", sentinel_report),
                patch.object(hp, "_OUTPUT_HEARTBEAT", sentinel_heartbeat),
            ):
                return hp.run_publisher()

    def test_empty_candidate_source_fails_closed(self):
        """Empty candidates → fail_closed, universe not written."""
        shadow = _minimal_shadow_universe([])
        shadow["candidates"] = []
        report = self._run_with_shadow(shadow)
        vs = report.get("validation_summary") or {}
        self.assertEqual(vs.get("overall_status"), "fail")
        aw = report.get("atomic_write_summary") or {}
        self.assertFalse(aw.get("universe_written"))
        self.assertFalse(aw.get("manifest_written"))

    def test_missing_source_file_fails_closed(self):
        """Missing shadow universe → fail_closed."""
        report = self._run_with_missing_shadow()
        vs = report.get("validation_summary") or {}
        self.assertEqual(vs.get("overall_status"), "fail")

    def test_invalid_source_json_fails_closed(self):
        """Invalid JSON source → fail_closed."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            bad_json = os.path.join(tmpdir, "bad.json")
            with open(bad_json, "w") as f:
                f.write("NOT JSON {{{{")
            sentinel = os.path.join(tmpdir, "out.json")
            with (
                patch.object(hp, "_SHADOW_UNIVERSE_PATH", bad_json),
                patch.object(hp, "_OUTPUT_UNIVERSE", sentinel),
                patch.object(hp, "_OUTPUT_MANIFEST", sentinel),
                patch.object(hp, "_OUTPUT_REPORT", sentinel),
                patch.object(hp, "_OUTPUT_HEARTBEAT", os.path.join(tmpdir, "hb.json")),
            ):
                report = hp.run_publisher()
        vs = report.get("validation_summary") or {}
        self.assertEqual(vs.get("overall_status"), "fail")

    def test_executable_candidate_is_rejected(self):
        """Candidate with executable=true in execution_instructions is rejected or causes fail-closed."""
        shadow = _minimal_shadow_universe(["BAD"])
        cand = shadow["candidates"][0]
        cand["execution_instructions"]["executable"] = True
        report = self._run_with_shadow(shadow)
        # Either fail_closed (zero_accepted_candidates) or candidate rejected
        vs = report.get("validation_summary") or {}
        cs = report.get("candidate_summary") or {}
        source_errors = vs.get("source_errors") or []
        if vs.get("overall_status") == "fail":
            # universe source-level rejection
            self.assertTrue(len(source_errors) > 0 or cs.get("accepted_count", -1) == 0)
        else:
            # candidate was rejected but others passed; check rejected list
            self.assertEqual(cs.get("rejected_count", 0), 0)  # shadow-level check catches it

    def test_order_instruction_candidate_causes_validation_error(self):
        """Candidate with order_instruction set is caught by output validator."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        cand = {"symbol": "X", "route": "swing", "route_hint": ["swing"],
                "reason_to_care": "test", "source_labels": ["test"],
                "theme_ids": [], "risk_flags": [], "confirmation_required": [],
                "approval_status": "approved", "quota_group": "structural_position",
                "freshness_status": "fresh", "executable": False,
                "order_instruction": "BUY 100 SHARES", "live_output_changed": False}
        errors = hp._validate_output_candidate(cand)
        self.assertTrue(any("order_instruction" in e for e in errors))

    def test_missing_required_candidate_field_fails_validation(self):
        """Candidate missing required field is caught by output validator."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        cand = {"symbol": "Y", "route": "swing", "route_hint": ["swing"]}
        errors = hp._validate_output_candidate(cand)
        self.assertTrue(len(errors) > 0)

    def test_secrets_exposed_true_fails_safety_check(self):
        """Publisher safety block has secrets_exposed=false hardcoded."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        self.assertIs(hp._SAFETY["secrets_exposed"], False)

    def test_env_values_logged_true_fails_safety_check(self):
        """Publisher safety block has env_values_logged=false hardcoded."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        self.assertIs(hp._SAFETY["env_values_logged"], False)

    def test_live_output_changed_true_fails_safety_check(self):
        """Publisher safety block has live_output_changed=false hardcoded."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        self.assertIs(hp._SAFETY["live_output_changed"], False)

    def test_invalid_output_does_not_overwrite_valid_file(self):
        """Fail-closed cycle: universe and manifest not overwritten."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            # Write a "valid" sentinel universe
            sentinel_universe = os.path.join(tmpdir, "active_opportunity_universe.json")
            sentinel_manifest = os.path.join(tmpdir, "current_manifest.json")
            original_content = {"sentinel": True}
            with open(sentinel_universe, "w") as f:
                json.dump(original_content, f)
            with open(sentinel_manifest, "w") as f:
                json.dump(original_content, f)

            # Run publisher with missing source — should fail closed
            missing = os.path.join(tmpdir, "nonexistent.json")
            with (
                patch.object(hp, "_SHADOW_UNIVERSE_PATH", missing),
                patch.object(hp, "_OUTPUT_UNIVERSE", sentinel_universe),
                patch.object(hp, "_OUTPUT_MANIFEST", sentinel_manifest),
                patch.object(hp, "_OUTPUT_REPORT", os.path.join(tmpdir, "report.json")),
                patch.object(hp, "_OUTPUT_HEARTBEAT", os.path.join(tmpdir, "hb.json")),
            ):
                hp.run_publisher()

            # Sentinel files must be unchanged
            with open(sentinel_universe) as f:
                result = json.load(f)
            self.assertTrue(result.get("sentinel"))

            with open(sentinel_manifest) as f:
                result = json.load(f)
            self.assertTrue(result.get("sentinel"))

    def test_heartbeat_only_updates_on_success(self):
        """Heartbeat written in fail state has validation_status=fail."""
        report = self._run_with_missing_shadow()
        vs = report.get("validation_summary") or {}
        self.assertEqual(vs.get("overall_status"), "fail")
        hs = report.get("heartbeat_summary") or {}
        # heartbeat was written (fail state)
        self.assertTrue(hs.get("written"))

    def test_fail_diagnostic_written_on_failed_publish(self):
        """Fail diagnostic file written on publish failure."""
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            diag_path = hp._write_fail_diagnostic("test_reason", {"info": "test"})
            # The function returns the path — we can't check tmpdir but we verify it ran
            self.assertIn(".fail_", diag_path)

    def test_tmp_file_used_in_atomic_write(self):
        """Atomic write creates .tmp file then renames."""
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            target = os.path.join(tmpdir, "out.json")
            hp._write_atomic(target, {"test": True})
            # tmp file cleaned up
            self.assertFalse(os.path.exists(target + ".tmp"))
            # final file present
            self.assertTrue(os.path.exists(target))
            with open(target) as f:
                data = json.load(f)
            self.assertTrue(data.get("test"))


# ---------------------------------------------------------------------------
# Group 8 — Atomic write policy
# ---------------------------------------------------------------------------

class TestAtomicWritePolicy(unittest.TestCase):
    """Group 8: Atomic write guarantees."""

    def test_atomic_write_creates_valid_json(self):
        """_write_atomic produces valid, readable JSON."""
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            path = os.path.join(tmpdir, "test.json")
            payload = {"key": "value", "number": 42, "nested": {"a": 1}}
            hp._write_atomic(path, payload)
            with open(path) as f:
                result = json.load(f)
            self.assertEqual(result["key"], "value")
            self.assertEqual(result["number"], 42)

    def test_atomic_write_no_tmp_left_behind(self):
        """No .tmp file left after successful write."""
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            path = os.path.join(tmpdir, "test.json")
            hp._write_atomic(path, {"x": 1})
            self.assertFalse(os.path.exists(path + ".tmp"))

    def test_atomic_write_creates_parent_dirs(self):
        """_write_atomic creates intermediate directories."""
        import handoff_publisher as hp
        with tempfile.TemporaryDirectory() as tmpdir:
            path = os.path.join(tmpdir, "deep", "dir", "test.json")
            hp._write_atomic(path, {"y": 2})
            self.assertTrue(os.path.exists(path))


# ---------------------------------------------------------------------------
# Group 9 — Import safety (AST)
# ---------------------------------------------------------------------------

class TestImportSafety(unittest.TestCase):
    """Group 9: handoff_publisher.py does not import forbidden modules."""

    def _publisher_imports(self) -> set[str]:
        src = open(os.path.join(_ROOT, "handoff_publisher.py")).read()
        tree = ast.parse(src)
        names: set[str] = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    names.add(alias.name.split(".")[0])
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    names.add(node.module.split(".")[0])
        return names

    def test_publisher_does_not_import_bot_trading(self):
        self.assertNotIn("bot_trading", self._publisher_imports())

    def test_publisher_does_not_import_scanner(self):
        self.assertNotIn("scanner", self._publisher_imports())

    def test_publisher_does_not_import_orders_core(self):
        self.assertNotIn("orders_core", self._publisher_imports())

    def test_publisher_does_not_import_guardrails(self):
        self.assertNotIn("guardrails", self._publisher_imports())

    def test_publisher_does_not_import_bot_ibkr(self):
        self.assertNotIn("bot_ibkr", self._publisher_imports())

    def test_publisher_does_not_import_provider_fetch_tester(self):
        self.assertNotIn("provider_fetch_tester", self._publisher_imports())

    def test_publisher_does_not_import_market_intelligence(self):
        self.assertNotIn("market_intelligence", self._publisher_imports())

    def test_publisher_does_not_import_apex_orchestrator(self):
        self.assertNotIn("apex_orchestrator", self._publisher_imports())

    def test_publisher_does_not_import_advisory_reporter(self):
        self.assertNotIn("advisory_reporter", self._publisher_imports())

    def test_publisher_does_not_import_advisory_log_reviewer(self):
        self.assertNotIn("advisory_log_reviewer", self._publisher_imports())

    def test_publisher_does_not_import_backtest_intelligence(self):
        self.assertNotIn("backtest_intelligence", self._publisher_imports())


# ---------------------------------------------------------------------------
# Group 10 — Regression
# ---------------------------------------------------------------------------

class TestSprintRegression(unittest.TestCase):
    """Group 10: Sprint 7E and 7C files remain valid."""

    def test_sprint7e_wiring_integration_module_exists(self):
        """test_handoff_wiring_integration.py still exists."""
        self.assertTrue(
            os.path.exists(
                os.path.join(_ROOT, "tests/test_handoff_wiring_integration.py")
            )
        )

    def test_handoff_candidate_adapter_still_exists(self):
        """handoff_candidate_adapter.py still present."""
        self.assertTrue(
            os.path.exists(os.path.join(_ROOT, "handoff_candidate_adapter.py"))
        )

    def test_handoff_reader_load_production_handoff_present(self):
        """handoff_reader.load_production_handoff still exists."""
        sys.path.insert(0, _ROOT)
        import handoff_reader
        self.assertTrue(callable(handoff_reader.load_production_handoff))

    def test_paper_comparison_report_still_valid(self):
        """paper_handoff_comparison_report.json still passes validator."""
        sys.path.insert(0, _ROOT)
        import intelligence_schema_validator as isv
        path = os.path.join(_ROOT, "data/live/paper_handoff_comparison_report.json")
        if os.path.exists(path):
            result = isv.validate_paper_handoff_comparison_report(path)
            self.assertTrue(result.ok, f"Sprint 7C regression: {result.errors}")

    def test_paper_manifest_still_valid(self):
        """paper_current_manifest.json still passes validator."""
        sys.path.insert(0, _ROOT)
        import intelligence_schema_validator as isv
        path = os.path.join(_ROOT, "data/live/paper_current_manifest.json")
        if os.path.exists(path):
            result = isv.validate_paper_manifest(path)
            self.assertTrue(result.ok, f"Sprint 7B regression: {result.errors}")

    def test_enable_handoff_flag_still_false(self):
        """enable_active_opportunity_universe_handoff must remain false."""
        sys.path.insert(0, _ROOT)
        import config
        self.assertFalse(
            config.CONFIG.get("enable_active_opportunity_universe_handoff", False)
        )


# ---------------------------------------------------------------------------
# Smoke
# ---------------------------------------------------------------------------

@pytest.mark.smoke
class TestSmokeSpotCheck(unittest.TestCase):
    """Smoke: quick end-to-end structure checks for Sprint 7F."""

    def test_smoke_passes_for_7f(self):
        """Sprint 7F smoke: publisher exists, outputs valid, flag false."""
        sys.path.insert(0, _ROOT)
        import handoff_publisher as hp
        import intelligence_schema_validator as isv

        # Publisher has correct public API
        self.assertTrue(callable(hp.run_publisher))

        # Validators for Sprint 7F files exist
        self.assertTrue(callable(isv.validate_prod_active_universe))
        self.assertTrue(callable(isv.validate_prod_manifest))
        self.assertTrue(callable(isv.validate_handoff_publisher_report))
        self.assertTrue(callable(isv.validate_handoff_publisher_heartbeat))

        # All four output files pass their validators
        result = isv.validate_prod_active_universe(
            os.path.join(_ROOT, "data/live/active_opportunity_universe.json")
        )
        self.assertTrue(result.ok, f"prod universe: {result.errors}")

        result = isv.validate_prod_manifest(
            os.path.join(_ROOT, "data/live/current_manifest.json")
        )
        self.assertTrue(result.ok, f"prod manifest: {result.errors}")

        result = isv.validate_handoff_publisher_report(
            os.path.join(_ROOT, "data/live/handoff_publisher_report.json")
        )
        self.assertTrue(result.ok, f"publisher report: {result.errors}")

        result = isv.validate_handoff_publisher_heartbeat(
            os.path.join(_ROOT, "data/heartbeats/handoff_publisher.json")
        )
        self.assertTrue(result.ok, f"heartbeat: {result.errors}")

        # Flag remains false
        import config
        self.assertFalse(config.CONFIG.get("enable_active_opportunity_universe_handoff", False))
