# ╔══════════════════════════════════════════════════════════════╗
# ║   <>  DECIFER  —  ic/storage.py                             ║
# ║   Weight persistence: read current weights, append weekly   ║
# ║   history, and orchestrate the full weekly recompute        ║
# ║   (update_ic_weights).                                      ║
# ║   Inventor: AMIT CHOPRA                                      ║
# ╚══════════════════════════════════════════════════════════════╝

import json
import os
import threading
from datetime import UTC, datetime

from ic.constants import (
    DIMENSIONS,
    EQUAL_WEIGHTS,
    IC_HISTORY_FILE,
    IC_WEIGHTS_FILE,
    _N,
    _ic_cfg,
    log,
)
from ic.core import compute_rolling_ic, normalize_ic_weights
from ic.data import _load_signal_records

# RB-7: Protect ic_weights.json against concurrent reads during a write.
# update_ic_weights() runs on the weekly review background thread while
# _get_edge_gate_adj() reads from the main scan loop. The write is already
# atomic (os.replace), so the risk window is tiny — but a thread-local lock
# eliminates it entirely at zero cost.
_ic_weights_lock = threading.Lock()


def get_current_weights() -> dict:
    """
    Return the current IC weights from the on-disk cache.

    Falls back to equal weights if:
    - The cache file does not exist
    - The file is malformed / missing dimensions
    - The weight vector does not sum to ~1.0
    """
    if not os.path.exists(IC_WEIGHTS_FILE):
        return dict(EQUAL_WEIGHTS)
    try:
        with _ic_weights_lock:  # RB-7: serialise against concurrent update_ic_weights write
            with open(IC_WEIGHTS_FILE) as f:
                data = json.load(f)
        weights = data.get("weights", {})
        if not all(d in weights for d in DIMENSIONS):
            return dict(EQUAL_WEIGHTS)
        total = sum(weights.values())
        if abs(total - 1.0) > 0.05:
            return dict(EQUAL_WEIGHTS)
        return {d: float(weights[d]) for d in DIMENSIONS}
    except Exception as e:
        log.warning("get_current_weights: load failed: %s", e)
        return dict(EQUAL_WEIGHTS)


def update_ic_weights(
    signals_log_path: str | None = None,
    historical_log_path: str | None = None,
) -> dict:
    """
    Recompute IC weights, write to cache, append to history log.

    Returns the new normalised weight dict.
    Should be called once per week (Sunday review cycle).

    historical_log_path
        Optional path to signals_log_historical.jsonl generated by
        backtest_signals.py.  When provided, historical records are merged
        with live records for a statistically richer IC estimate.
    """
    raw_ic = compute_rolling_ic(signals_log_path, historical_log_path=historical_log_path)
    weights, ic_meta = normalize_ic_weights(raw_ic)

    all_none = all(v is None for v in raw_ic.values())
    _eq_weight = 1.0 / _N
    # Tolerance-based comparison — exact float equality fails because 1/N
    # (0.08333…3) and round(1/N, 10) (0.08333333330) differ beyond ==.
    all_equal = _ic_cfg("force_equal_weights", False) or all(
        abs(weights.get(d, 0.0) - _eq_weight) < 1e-9 for d in DIMENSIONS
    )

    n_records = len(_load_signal_records(signals_log_path))

    record = {
        "updated": datetime.now(UTC).isoformat(),
        "raw_ic": {d: (raw_ic.get(d) if raw_ic.get(d) is not None else None) for d in DIMENSIONS},
        "weights": weights,
        "n_records": n_records,
        "using_equal_weights": all_none or all_equal,
        "noise_floor_applied": ic_meta["noise_floor_applied"],
        "dimensions_suppressed": ic_meta["dimensions_suppressed"],
        "hhi_capped": ic_meta["hhi_capped"],
    }

    os.makedirs(os.path.dirname(IC_WEIGHTS_FILE), exist_ok=True)

    # Atomic write for the current weights file, serialised with the read lock.
    import tempfile

    dir_ = os.path.dirname(IC_WEIGHTS_FILE)
    fd, tmp = tempfile.mkstemp(dir=dir_, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(record, f, indent=2)
        with _ic_weights_lock:  # RB-7: hold lock only for the rename, not the full write
            os.replace(tmp, IC_WEIGHTS_FILE)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise

    # Append-only history
    with open(IC_HISTORY_FILE, "a") as f:
        f.write(json.dumps(record) + "\n")

    log.info(
        "IC weights updated (n=%d, equal=%s): %s",
        n_records,
        record["using_equal_weights"],
        ", ".join(f"{d}={weights[d]:.3f}" for d in DIMENSIONS),
    )

    # Auto-disable / auto-enable dimensions based on consecutive IC history.
    # Lazy import to break the storage ↔ monitoring cycle:
    # monitoring._check_ic_auto_disable calls storage.get_ic_weight_history.
    from ic.monitoring import _check_ic_auto_disable

    _check_ic_auto_disable(raw_ic)

    return weights


def get_ic_weight_history(last_n: int = 4) -> list:
    """
    Return the last `last_n` weekly IC weight snapshots for trend display.
    Each entry has keys: updated, weights, raw_ic, n_records, using_equal_weights.
    """
    if not os.path.exists(IC_HISTORY_FILE):
        return []
    records = []
    try:
        with open(IC_HISTORY_FILE) as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        records.append(json.loads(line))
                    except Exception:
                        pass
    except Exception:
        return []
    return records[-last_n:]
